/**
 * Single source of truth for the site's pages.
 *
 * Every entry here automatically gets:
 *  - a client route in English (`path`) and Bulgarian (`/bg` + `path`)
 *  - a prerendered static HTML file per language (dist/<path>/index.html)
 *  - <title>, meta description, canonical, Open Graph, Twitter and hreflang tags
 *  - an entry (with hreflang alternates) in the generated sitemap.xml
 *  - a link in the main navigation, if `navKey` is set
 *
 * To add a page: create `pages/<Page>.tsx` (default export) and add an entry below.
 *
 * This module must stay free of React/DOM imports: it is used by the browser
 * bundle, the SSR bundle and the build-time prerender step.
 */

import { DOGS, DOG_PHOTO_SIZES, HOME_HERO_IMAGE } from './constants';
import { webpSrcSet, webpUrl } from './utils/images';

export type Language = 'en' | 'bg';

export const LANGUAGES: readonly Language[] = ['en', 'bg'];
export const DEFAULT_LANGUAGE: Language = 'en';

/** Production origin (apex custom domain from public/CNAME). No trailing slash. */
export const SITE_URL = 'https://stellamaris.dog';

/** URL prefix per language. The default language lives at the site root. */
const LANGUAGE_PREFIX: Record<Language, string> = { en: '', bg: '/bg' };

export const OG_LOCALE: Record<Language, string> = { en: 'en_US', bg: 'bg_BG' };

/** Each language's name in its own language, for the language switcher. */
export const LANGUAGE_NAMES: Record<Language, string> = { en: 'English', bg: 'Български' };

export interface PageMeta {
  readonly title: string;
  readonly description: string;
}

export interface PreloadImage {
  readonly href: string;
  readonly type: string;
  /** Must equal the <img>/<source> srcset and sizes, or the browser downloads the image twice. */
  readonly srcset?: string;
  readonly sizes?: string;
}

/**
 * Link-preview image for every page (Open Graph, Twitter, JSON-LD in index.html).
 * Generated by scripts/encode-images.mjs (1200x630 JPEG, well under WhatsApp's preview size limit).
 */
export const OG_IMAGE = {
  url: `${SITE_URL}/images/og-image.jpg`,
  width: 1200,
  height: 630,
  type: 'image/jpeg',
  alt: {
    en: 'Steli and Mitko of Stella Maris Kennel with their Portuguese Water Dogs and a litter of puppies',
    bg: 'Стели и Митко от развъдник Стела Марис с техните португалски водни кучета и кученцата от едно кучило',
  } as Readonly<Record<Language, string>>,
} as const;

/** Preload for the home page hero (its LCP image), matching pages/Home.tsx exactly. */
const HOME_HERO_PRELOAD: PreloadImage = {
  href: webpUrl(HOME_HERO_IMAGE.src),
  type: 'image/webp',
  srcset: webpSrcSet(HOME_HERO_IMAGE.src),
  sizes: HOME_HERO_IMAGE.sizes,
};

/** Preload for the first dog's photo on Our Dogs (its LCP image), matching pages/OurDogs.tsx exactly. */
const DOGS_PHOTO_PRELOAD: PreloadImage = {
  href: webpUrl(DOGS[0].image),
  type: 'image/webp',
  srcset: webpSrcSet(DOGS[0].image),
  sizes: DOG_PHOTO_SIZES,
};

export interface RouteDef {
  /** Stable identifier used in code (e.g. `routePath('contact', lang)`). */
  readonly id: string;
  /** Language-neutral path with leading and trailing slash, e.g. '/about/'. */
  readonly path: string;
  /** Component file name in pages/ without extension, e.g. 'About' → pages/About.tsx. */
  readonly page: string;
  /** Translation key of the main-navigation label. Omit to keep the page out of the nav. */
  readonly navKey?: string;
  /** Per-language <title> and meta description. */
  readonly meta: Readonly<Record<Language, PageMeta>>;
  /** High-priority image preloads emitted only on this route (LCP hints). */
  readonly preloadImages?: readonly PreloadImage[];
  /** Set to false to exclude from the sitemap and mark the page noindex. Defaults to true. */
  readonly indexable?: boolean;
}

export const ROUTES = [
  {
    id: 'home',
    path: '/',
    page: 'Home',
    navKey: 'nav.home',
    preloadImages: [HOME_HERO_PRELOAD],
    meta: {
      en: {
        title: 'Portuguese Water Dog Breeder in Sofia, Bulgaria | Stella Maris',
        description:
          'Stella Maris Kennel: FCI registered (166/2024) Portuguese Water Dog breeder in Sofia, Bulgaria. Health-tested champion parents, puppies raised at home.',
      },
      bg: {
        title: 'Португалско водно куче – развъдник Стела Марис, София',
        description:
          'Стела Марис – регистриран във FCI развъдник (№ 166/2024) на португалско водно куче, София. Здравно изследвани родители шампиони; кученца, отгледани у дома.',
      },
    },
  },
  {
    id: 'about',
    path: '/about/',
    page: 'About',
    navKey: 'nav.our_story',
    meta: {
      en: {
        title: 'Our Story – Family Portuguese Water Dog Kennel | Stella Maris',
        description:
          'Meet Steli and Mitko, the family behind Stella Maris, an FCI registered Portuguese Water Dog kennel near Vitosha in Sofia, Bulgaria. Our dogs live with us.',
      },
      bg: {
        title: 'За нас – семеен развъдник на португалско водно куче | Стела Марис',
        description:
          'Стели и Митко – семейството зад Стела Марис, регистриран във FCI развъдник на португалско водно куче край Витоша, София. Кучетата ни живеят у дома с нас.',
      },
    },
  },
  {
    id: 'dogs',
    path: '/dogs/',
    page: 'OurDogs',
    navKey: 'nav.our_dogs',
    preloadImages: [DOGS_PHOTO_PRELOAD],
    meta: {
      en: {
        title: 'Our Portuguese Water Dogs: Arthur & Riva Rosa | Stella Maris',
        description:
          'Meet our breeding pair, Arthur Rubinstein Do Veleiro Nagual and Riva Rosa Do Lusiadas: show titles, genetic health tests and temperament. Sofia, Bulgaria.',
      },
      bg: {
        title: 'Нашите португалски водни кучета: Артър и Рива Роза | Стела Марис',
        description:
          'Нашата развъдна двойка Arthur Rubinstein Do Veleiro Nagual и Riva Rosa Do Lusiadas: титли от изложби, резултати от генетични тестове и темперамент. София.',
      },
    },
  },
  {
    id: 'puppies',
    path: '/puppies/',
    page: 'Puppies',
    navKey: 'nav.puppies',
    meta: {
      en: {
        title: 'Portuguese Water Dog Puppies & Waitlist | Stella Maris, Bulgaria',
        description:
          'Portuguese Water Dog puppies from Stella Maris Kennel, Sofia, Bulgaria: our next and past litters, where our puppies live and how the waitlist works.',
      },
      bg: {
        title: 'Кученца португалско водно куче в България | Стела Марис',
        description:
          'Кученца португалско водно куче от развъдник Стела Марис, София: следващото и предишните ни кучила, къде живеят кученцата и как работи списъкът с чакащи.',
      },
    },
  },
  {
    id: 'faq',
    path: '/faq/',
    page: 'FAQ',
    navKey: 'nav.faq',
    meta: {
      en: {
        title: 'Portuguese Water Dog FAQ: Breed, Puppies & Travel | Stella Maris',
        description:
          'Portuguese Water Dog FAQ: temperament, exercise, grooming, allergies, size, our waitlist, go-home age and EU travel rules for puppies from Bulgaria.',
      },
      bg: {
        title: 'Чести въпроси за португалското водно куче | Стела Марис',
        description:
          'Въпроси за португалското водно куче: характер, движение, козина, алергии и размер, както и списъкът с чакащи, възрастта за вземане и пътуването в ЕС.',
      },
    },
  },
  {
    id: 'contact',
    path: '/contact/',
    page: 'Contact',
    navKey: 'nav.contact',
    meta: {
      en: {
        title: 'Contact Stella Maris – Portuguese Water Dog Breeder, Sofia',
        description:
          'Contact Stella Maris Kennel in Sofia about Portuguese Water Dog puppies, the waitlist or stud service. Email hello@stellamaris.dog, call +359 897 014 015.',
      },
      bg: {
        title: 'Контакти – развъдник на португалско водно куче, София | Стела Марис',
        description:
          'Свържете се с развъдник Стела Марис в София за кученца португалско водно куче, списъка с чакащи или покриване: hello@stellamaris.dog, +359 897 014 015.',
      },
    },
  },
  {
    id: 'privacy',
    path: '/privacy/',
    page: 'Privacy',
    // Linked from the footer and the cookie banner, not from the main navigation.
    meta: {
      en: {
        title: 'Privacy Policy | Stella Maris',
        description:
          'How Stella Maris Kennel handles your personal data: the contact form, Google Ads cookies (only with your consent), the map, hosting and your GDPR rights.',
      },
      bg: {
        title: 'Политика за поверителност | Стела Марис',
        description:
          'Как Стела Марис обработва личните ви данни: формата за контакт, бисквитките на Google Ads (само със съгласие), картата, хостинга и правата ви по ОРЗД.',
      },
    },
  },
] as const satisfies readonly RouteDef[];

export type AppRoute = (typeof ROUTES)[number];
export type RouteId = AppRoute['id'];

/** Meta for the catch-all "page not found" view (always noindex). */
export const NOT_FOUND_META: Readonly<Record<Language, PageMeta>> = {
  en: {
    title: 'Page not found | Stella Maris',
    description: 'The page you are looking for does not exist. Visit Stella Maris Kennel, Portuguese Water Dog breeder in Sofia, Bulgaria.',
  },
  bg: {
    title: 'Страницата не е намерена | Стела Марис',
    description: 'Търсената страница не съществува. Посетете развъдник Стела Марис – португалско водно куче, София, България.',
  },
};

/**
 * Pages of the previous (Jekyll) site that are still indexed or linked.
 * GitHub Pages cannot send 301s, so the build writes a small noindex
 * redirect stub (canonical + meta refresh + JS) for each of them.
 * Key: old file name; value: the route it now lives at.
 */
export const LEGACY_PAGES: Readonly<Record<string, RouteId>> = {
  'puppies.html': 'puppies',
  'litters.html': 'puppies',
  'dogs.html': 'dogs',
  'story.html': 'about',
  // The old 'About The Breed' page: the breed questions now live in the FAQ's 'The breed' section.
  'breed.html': 'faq',
  'apply.html': 'contact',
  'contact.html': 'contact',
  'thanks.html': 'contact',
};

/**
 * Language folders of the old site (jekyll-multiple-languages-plugin) and the
 * language each now maps to. '' is the root (English). The old Spanish section
 * has no counterpart, so it maps to English. /bg/ itself is a real route now.
 */
export const LEGACY_LANGUAGE_DIRS: Readonly<Record<string, Language>> = { '': 'en', 'bg/': 'bg', 'es/': 'en' };

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export const isIndexable = (route: RouteDef): boolean => route.indexable !== false;

export const getRoute = (id: RouteId): AppRoute => {
  const route = ROUTES.find((r) => r.id === id);
  if (!route) throw new Error(`Unknown route id: ${id}`);
  return route;
};

/** Prefix a language-neutral path ('/about/') for a language ('/bg/about/'). */
export const localizePath = (path: string, lang: Language): string => `${LANGUAGE_PREFIX[lang]}${path}`;

/** Path of a route in a language, always with a trailing slash. */
export const routePath = (id: RouteId, lang: Language): string => localizePath(getRoute(id).path, lang);

export const absoluteUrl = (path: string): string => `${SITE_URL}${path}`;

const withTrailingSlash = (path: string): string => (path.endsWith('/') ? path : `${path}/`);

export interface LocationMatch {
  lang: Language;
  /** The matched route, or null when the path is not a known page (404). */
  route: AppRoute | null;
}

/** Resolve a URL pathname to its language and route. Pure: safe on server and client. */
export const matchPath = (pathname: string): LocationMatch => {
  let lang: Language = DEFAULT_LANGUAGE;
  let rest = pathname || '/';
  for (const candidate of LANGUAGES) {
    const prefix = LANGUAGE_PREFIX[candidate];
    if (prefix && (rest === prefix || rest.startsWith(`${prefix}/`))) {
      lang = candidate;
      rest = rest.slice(prefix.length) || '/';
      break;
    }
  }
  // /index.html and /about/index.html are served by static hosting too: treat them as / and /about/.
  const normalized = withTrailingSlash(rest.replace(/\/index\.html$/, '/'));
  const route = ROUTES.find((r) => r.path === normalized) ?? null;
  return { lang, route };
};

/**
 * Where the language switcher should point: the same page in `lang`, or that
 * language's home page when the current path is not a known page.
 */
export const switchLanguagePath = (pathname: string, lang: Language): string => {
  const { route } = matchPath(pathname);
  return route ? routePath(route.id, lang) : routePath('home', lang);
};

/**
 * Map a URL from the old HashRouter site ('#/puppies?x=1') to its new path
 * ('/puppies/?x=1'). Returns null when the hash is not an old route link.
 */
export const legacyHashToPath = (hash: string): string | null => {
  if (!hash.startsWith('#/')) return null;
  const raw = hash.slice(1);
  const queryIndex = raw.indexOf('?');
  const pathname = queryIndex === -1 ? raw : raw.slice(0, queryIndex);
  const search = queryIndex === -1 ? '' : raw.slice(queryIndex);
  const { lang, route } = matchPath(pathname);
  return `${route ? routePath(route.id, lang) : routePath('home', lang)}${search}`;
};
