// Generated by scripts/encode-images.mjs from assets-src/images/. Do not edit by hand.

export interface ImageInfo {
  /** Intrinsic size of the largest variant (<name>.webp). */
  readonly width: number;
  readonly height: number;
  /** Available WebP widths, ascending; the last one is the largest variant. */
  readonly widths: readonly number[];
}

/** Keyed by the image's public JPEG URL, e.g. '/images/arthy.jpg'. */
export const IMAGE_MANIFEST: Readonly<Record<string, ImageInfo>> = {
  "/images/arthy.jpg": { width: 1280, height: 1600, widths: [480, 720, 960, 1280] },
  "/images/family.jpg": { width: 1600, height: 1066, widths: [480, 960, 1600] },
  "/images/gallery-kings/kings-litter-brown-puppy.jpg": { width: 607, height: 1080, widths: [480, 607] },
  "/images/gallery-kings/kings-litter-newborn-puppy.jpg": { width: 607, height: 1080, widths: [480, 607] },
  "/images/gallery-story/portuguese-water-dog-beach-walk.jpg": { width: 1440, height: 1080, widths: [480, 960, 1440] },
  "/images/gallery-story/portuguese-water-dog-beach.jpg": { width: 810, height: 1080, widths: [480, 810] },
  "/images/gallery-story/portuguese-water-dog-family-pisa.jpg": { width: 810, height: 1080, widths: [480, 810] },
  "/images/gallery-story/portuguese-water-dog-kayak.jpg": { width: 1600, height: 901, widths: [480, 960, 1600] },
  "/images/gallery-story/portuguese-water-dog-paddleboard.jpg": { width: 1440, height: 1080, widths: [480, 960, 1440] },
  "/images/gallery-story/portuguese-water-dog-show-podium.jpg": { width: 719, height: 1080, widths: [480, 719] },
  "/images/gallery-story/portuguese-water-dog-sofa.jpg": { width: 608, height: 1080, widths: [480, 608] },
  "/images/gallery-story/portuguese-water-dogs-forest-walk.jpg": { width: 608, height: 1080, widths: [480, 608] },
  "/images/gallery-story/portuguese-water-dogs-mountain-town.jpg": { width: 1600, height: 747, widths: [480, 960, 1600] },
  "/images/gallery-story/portuguese-water-dogs-seaside-wall.jpg": { width: 504, height: 1080, widths: [504] },
  "/images/gallery-story/portuguese-water-dogs-water-rescue-training.jpg": { width: 1032, height: 1055, widths: [480, 1032] },
  "/images/gallery-story/portuguese-water-dogs-with-child.jpg": { width: 608, height: 1080, widths: [480, 608] },
  "/images/puppies.jpg": { width: 1600, height: 1067, widths: [480, 960, 1600] },
  "/images/riva.jpg": { width: 1200, height: 1600, widths: [480, 720, 960, 1200] },
  "/images/steliandpuppy.jpg": { width: 640, height: 427, widths: [640] },
};
