/**
 * Helpers for the responsive images generated by scripts/encode-images.mjs.
 * Pure (no React/DOM): used by components/Picture.tsx and by routes.ts for LCP preloads.
 *
 * An image is referred to by its public JPEG URL, e.g. '/images/arthy.jpg'. Next to it the
 * build serves '/images/arthy.webp' (largest) and '/images/arthy-480.webp', '-960.webp' (narrower).
 */
import { IMAGE_MANIFEST, type ImageInfo } from './imageManifest';

export type { ImageInfo };

/** Intrinsic size and available widths, or undefined for an image the encoder does not know. */
export const getImageInfo = (src: string): ImageInfo | undefined => IMAGE_MANIFEST[src];

const encodeUrl = (url: string): string => encodeURI(url);

const stem = (src: string): string => src.replace(/\.(jpe?g|png)$/i, '');

/** URL of one WebP variant; the largest width has no suffix. */
export const webpUrl = (src: string, width?: number): string => {
  const info = getImageInfo(src);
  const suffix = info && width !== undefined && width !== info.width ? `-${width}` : '';
  return encodeUrl(`${stem(src)}${suffix}.webp`);
};

/** `srcset` value listing every WebP variant, or undefined when the image has none. */
export const webpSrcSet = (src: string): string | undefined => {
  const info = getImageInfo(src);
  if (!info) return undefined;
  return info.widths.map((w) => `${webpUrl(src, w)} ${w}w`).join(', ');
};

/** URL of the JPEG fallback (same as `src`, URL-encoded). */
export const fallbackUrl = (src: string): string => encodeUrl(src);
